export const GET_ITEMS = "GET_ITEMS";
export const ADD_ITEM = "ADD_ITEM";
export const DELETE_ITEM = "DELETE_ITEM";
export const ITEMS_LOADING = "ITEMS_LOADING";

export const HANDLE_ADD_EVENT_MODAL = "HANDLE_ADD_EVENT_MODAL";
export const HANDLE_EDIT_EVENT_MODAL = "HANDLE_EDIT_EVENT_MODAL";

export const ADD_EVENT = "ADD_EVENT";
export const DELETE_EVENT = 'DELETE_EVENT'
